### PR TITLE
Improve connection logging

### PR DESCRIPTION
**Pull request by palto42**
This PR implements the improvements suggested in #83.

Connection errors are only logged once and subsequent follow-up errors from trying to parse empty responses are skipped.

Other minor changes:

- added/corrected some type hints
- formatted code with black
- changed some unnecessary `elif` conditions to `if` as per `pylint` suggestion
- replaced deprecated logger `warn` with `warning`
- sorted imports using `isort`

### CODE REVIEW

**Comment by kbialek** [comment]
Looks good. I will test it. For the future, for better readability, please do not mix implementation and formatting changes in this same commit

**Comment by kbialek** [comment]
Beta image created `ghcr.io/kbialek/deye-inverter-mqtt:2023.06.1-beta-1`

**Comment by kbialek** [comment]
@palto42 Please merge `main` into this PR. Thanks!

**Comment by palto42** [comment]
@kbialek  I have merged `main` into my branch [log_connect_error](https://github.com/palto42/deye-inverter-mqtt/tree/log_connect_error) , but for some reason this commit is not updated in this PR.
Any idea what blocks it? If not, I may nee to close and re-open it.

**Comment by palto42** [comment]
@kbialek I have merged main as requested, had to sort out some merge conflicts but looks good now.

**Comment by kbialek** [comment]
Included in beta image `ghcr.io/kbialek/deye-inverter-mqtt:2023.06.1-beta-2`

**Pull request merged**
