### PR TITLE
Compute DC Total Power for Micro inverters

### PR DESCRIPTION
**Pull request by kbialek**
Micro inverters do not report DC Total Power. Mitigate this by computing it as a sum of PV1,PV2,PV3,PV4 power metrics.

### CODE REVIEW

**Comment by kbialek** [comment]
@Antagor What do you think about this?

**Comment by Antagor** [comment]
You did a lot of work in this project. 
I wouldn't mind if there are a few zero values which are not needed, but as you have programmed everything.... 
Can it be that you have forgotten the variable for micro_DC_power at the end of sensors? 
Sorry, I did not understand the part with unit test.
If you create a beta I will run it tomorrow. 
Thanks for all your work

**Comment by kbialek** [comment]
> I wouldn't mind if there are a few zero values which are not needed, but as you have programmed everything.... 

It's a low hanging fruit, so why not :smile: 

> Can it be that you have forgotten the variable for micro_DC_power at the end of sensors? 

Of course I have forgotten. Thanks for pointing that out!

> Sorry, I did not understand the part with unit test. If you create a beta I will run it tomorrow. Thanks for all your work

There it is `ghcr.io/kbialek/deye-inverter-mqtt:2023.01.2-beta-4`

**Comment by Antagor** [comment]
Hello,
it could be a problem to send it twice:
2023-01-15 08:28:47,269 - DeyeDaemon - DEBUG - PV4 Production today: 0.0
2023-01-15 08:28:47,269 - DeyeDaemon - DEBUG - PV4 Total: 0.0
2023-01-15 08:28:47,270 - DeyeDaemon - DEBUG - DC Total Power: 0.0
2023-01-15 08:28:47,270 - DeyeDaemon - DEBUG - DC Total Power: 2.9
2023-01-15 08:28:47,271 - DeyeDaemon - DEBUG - Operating Power: 0.0
2023-01-15 08:28:47,271 - DeyeDaemon - DEBUG - AC Active Power: 5.0
2023-01-15 08:28:47,271 - DeyeDaemon - DEBUG - Radiator temperature: 68.0
And mybe you can add my addition to the temp -> 68 degree is to much in winter with 2.9 power
thanks

**Comment by kbialek** [comment]
> it could be a problem to send it twice:

Of course! Thanks for checking this!

**Pull request merged**
