### PR TITLE
New setting to explicitly enable plugins

### PR DESCRIPTION
**Pull request by hoegaarden**
This introduces a new config value `PLUGINS_ENABLED`, which is a list of plugins which should  be loaded after being discovered successfully.

Use-case:

A container image can be produced, shipping multiple plugins, but still giving users control over which ones get actually loaded.

### CODE REVIEW

**Comment by kbialek** [comment]
hi @hoegaarden, Why opt-out instead of opt-in? Or in other words why `PLUGINS_DISABLE` and not `PLUGINS_ENABLE`?

**Comment by hoegaarden** [comment]
Don't have a strong opinion on that.

To me it makes slightly more sense to, by default, load all plugins that happen to reside in the plugins directory, but allow users to selectively disable certain plugins.
FWIW, tho probably not super important: this keeps the current default behavior.

But again, no strong opinion.

**Comment by kbialek** [comment]
I prefer to focus on and specify what I need instead of what I do not need. Also, imagine what will happen when you release a new version of your image, with some new plugins bundled. They will be automatically activated. I doubt if that is desired.

**Review by kbialek — APPROVED** [review]

**Pull request merged**
